brew "salt"
brew "swig"
# lessons app needs this until we remove mimemagic dependency
brew "shared-mime-info"
brew "coreutils"
brew "heroku"
brew "wget"
brew "gpg"
brew "openssl"
brew "nginx"
brew "dnsmasq"
brew "postgresql"
brew "asdf"